services:
  database:
    container_name: comm-clinic-db
    image: postgres:16.9
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    tty: true
    ports:
      - 5432:5432

  server:
    container_name: comm-clinic-server
    depends_on:
      - database
    build:
      context: ./server-app
      target: dev
    volumes:
      - ./server-app:/app/
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 8000:8000
    command: npm run start:dev

  client:
    container_name: client-app
    depends_on:
      - server
    build:
      context: ./client-app
      target: dev
    volumes:
      - ./client-app:/app
      - /app/node_modules
    ports: 
      - 5173:5173
    command: npm run dev

volumes:
  db_data: